### ISSUE TITLE
Create History Page

### ISSUE THREAD

**Issue by ChesterHuey** [acmucsd-projects/fa2024-hack-team-2#25]
Description: A history page that displays the users previously swiped cloths and previously viewed users. This page should also include a filter on what appears first, the base filter is most recent.

Requirement's:
Show history items in a card-based layout.
Each card should include:
Thumbnail of the post or user.
Username (for user cards) or post title (for post cards).
Should be blank if nothing has been swiped on.

Tab Functionality:

The page must have tabs or toggle buttons to switch between:
Posts: Displays recently viewed posts.
Users: Displays recently viewed users (with swipe icons included).

Criteria:

Include tabs or toggles to switch between:
Posts: Displays recently viewed posts.
Users: Displays recently viewed users (with swipe interaction icons).
Navigation:

Implement navigation using React Router.
Users should be able to switch seamlessly between the History Page and other parts of the application.
Responsive Design:

The History Page must be fully responsive, adapting to different screen sizes (e.g., mobile, tablet, desktop).
Ensure the layout adjusts appropriately to maintain usability and aesthetics on all devices.

**Comment by ChesterHuey** [comment]
Make in component format.

**Comment by ChesterHuey** [comment]
PR: https://github.com/acmucsd-projects/fa2024-hack-team-2/pull/37#issue-2747008160

**Comment by OrigamiStarz** [comment]
Hello Chester, great job on the history component so far! I especially like how you implemented a gradient background for the cards.

Could you make the following changes? Let me know if I need to clarify any of them. Sorry for making the list so long :')
- [ ] Put the `ViewHistory.tsx` inside of the `components` folder instead of the `History` folder
- [ ] Remove the `Add Post` and `Add User` buttons
  - [ ] You shouldn't need to track the number of users/posts
- [ ] Show all posts initially instead of having the user add them
- [ ] Squares instead of rectangles for users
- [ ] Should be more user friendly 
  - [ ] Some way to see all 10 temporary posts/users, like scrolling
  - [ ] Fix margin issue (currently inconsistent between viewing posts versus viewing users)
- [ ] A way to indicate which button is active (ex. make the `Post` button darker when posts are displayed)
- [ ] Each card should be linked to a post or user profile (use dummy data, especially for posts)
- [ ] Remove the like button for users
- [ ] Indicate if the user likes the post (use dummy data to see if the user liked the post)
  - [ ] Suggestion: filled heart for liked, unfilled heart for disliked
  - [ ] Also consider moving the number of likes below the heart icon
- [ ] Consider removing gradient background for users
- [ ] Inside `ViewHistory.tsx`, use a div with absolute positioning surrounding its contents (to make it easier to integrate into other pages)
